# Generated by Django 4.2 on 2023-04-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='お名前')),
                ('email', models.EmailField(max_length=50, verbose_name='メールアドレス')),
                ('content', models.TextField(verbose_name='お問い合わせ内容')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
    ]
