# Generated by Django 4.2 on 2023-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_contacts_alter_category_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='タグ名')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.ManyToManyField(blank=True, to='bbs.tag', verbose_name='タグ'),
        ),
    ]
